#!/bin/bash

# Exit build script on first failure.
set -e

# Exit on unset variable.
set -u

# Generate and load the maps
mount -t bpf bpf /sys/fs/bpf

./xdp_loader --dev eth0 --force

# Run the backend
./backend