#!/bin/bash

# Exit build script on first failure.
set -e

# Exit on unset variable.
set -u

# Generate and load the maps
mkdir -p /sys/fs/bpf/eth0

make

./xdp_loader --dev eth0 --force

# # # Run the backend
./backend