version: "3"
services:

  tma_nginx:
    container_name: tma_nginx
    image: nginx:latest
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d:ro
      - ./nginx/log:/var/log/nginx
      - ./public:/public
    privileged: true
    depends_on:
      - tma_server

  tma_server:
    container_name: tma_server
    image: node:latest
    command: bash -c "cd /server && npm start"
    volumes:
      - ./server:/server:ro

  